[package]
name = "rspolib-testing"
version = "0.0.4"
edition = "2021"
description = "Testing utilities for rspolib."
license = "MIT"

[lib]
name = "rspolib_testing"
path = "src/lib.rs"

[dependencies]
rspolib = { path = ".." }

