[package]
name = "py-rspolib"
version = "0.0.1"
edition = "2021"
readme = "README.md"

[lib]
name = "rspolib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
rspolib = { path = "../rust" }
